<?php
declare(strict_types=1);
require __DIR__ . '/includes/actions.php';
$ingredients = active_ingredients(); $recipes = recipes_with_cost(); $editRecipe = isset($_GET['edit']) ? one('SELECT * FROM recipes WHERE id=?','i',[(int)$_GET['edit']]) : null; $editItems = $editRecipe ? recipe_items((int)$editRecipe['id']) : [];
$formItems = $editItems ?: [['ingredient_id'=>$ingredients[0]['id']??0,'quantity'=>1,'base_unit'=>$ingredients[0]['base_unit']??'gram']];
layout_start('Produk & Resep', 'products.php');
?>
<section class="page-hero"><div><p class="eyebrow">PRODUK / RESEP / BOM</p><h1>Produk dan resep</h1><p class="muted">Semua jumlah resep dikonversi ke satuan stok sebelum HPP dihitung.</p></div></section>
<div class="workspace"><section class="panel" id="recipe-form"><div class="panel-heading"><div><p class="eyebrow">RECIPE BUILDER</p><h2>Produk baru</h2></div><span class="badge">HPP terpusat</span></div>
<form method="post" action="products.php"><?=csrf_field()?><input type="hidden" name="action" value="<?=$editRecipe?'update_recipe':'add_recipe'?>"><?php if($editRecipe):?><input type="hidden" name="recipe_id" value="<?=$editRecipe['id']?>"><?php endif;?><label>Nama produk<input name="recipe_name" required value="<?=e($editRecipe['name']??'')?>" placeholder="Es Kopi Susu"></label><div id="ingredient-lines"><?php foreach($formItems as $item):?><div class="ingredient-line"><label>Bahan<select name="ingredient_id[]" required><?php foreach($ingredients as $i):?><option value="<?=$i['id']?>" <?=$i['id']==$item['ingredient_id']?'selected':''?>><?=e($i['name'])?> (<?=e($i['base_unit'])?>)</option><?php endforeach;?></select></label><label>Jumlah<input name="quantity[]" type="number" step="0.001" min="0.001" value="<?=e($item['quantity'])?>" required></label><label>Satuan<select name="unit[]"><?php foreach(array_keys(APP_UNITS) as $u):?><option <?=$u===$item['base_unit']?'selected':''?>><?=$u?></option><?php endforeach;?></select></label><button type="button" class="icon-button remove-line">×</button></div><?php endforeach;?></div><button class="button secondary" type="button" id="add-line">+ Tambah bahan</button><div class="form-grid compact"><label>Biaya alat<input name="equipment_cost" type="number" min="0" step="0.01" value="<?=e($editRecipe['equipment_cost']??'0')?>"></label><label>Operasional<input name="operational_cost" type="number" min="0" step="0.01" value="<?=e($editRecipe['operational_cost']??'0')?>"></label><label>Kemasan<input name="packaging_cost" type="number" min="0" step="0.01" value="<?=e($editRecipe['packaging_cost']??'0')?>"></label><label>Tier markup<select name="price_tier"><?php foreach(['murah','normal','mahal'] as $tier):?><option value="<?=$tier?>" <?=($editRecipe['price_tier']??'normal')===$tier?'selected':''?>><?=ucfirst($tier)?> (<?=markup_for($tier)?>%)</option><?php endforeach;?></select></label></div><button class="button primary full">Simpan produk</button><?php if($editRecipe):?><a class="button secondary full" href="products.php">Batal edit</a><?php endif;?></form></section>
<section class="panel"><div class="panel-heading"><div><p class="eyebrow">PRODUK AKTIF</p><h2><?=count($recipes)?> produk</h2></div><input class="table-search" data-filter-table="#product-table" placeholder="Cari produk..."></div><div class="table-scroll"><table id="product-table"><thead><tr><th>Produk</th><th>HPP</th><th>Harga jual</th><th>Aksi</th></tr></thead><tbody><?php foreach($recipes as $r):?><tr><td><strong><?=e($r['name'])?></strong><small>Markup <?=e($r['price_tier'])?></small></td><td><?=rupiah($r['hpp_live'])?></td><td><?=rupiah($r['selling_price'])?></td><td><a class="button secondary small" href="?edit=<?=$r['id']?>">Edit</a> <a class="button secondary small" href="pos.php?product=<?=$r['id']?>">Jual</a><form method="post" style="display:inline" onsubmit="return confirm('Nonaktifkan produk?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_recipe"><input type="hidden" name="recipe_id" value="<?=$r['id']?>"><button class="button danger small">Nonaktifkan</button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php layout_end(); ?>
